### ISSUE TITLE
Sometimes "The supplied file path doesn't exist" can happen

### ISSUE THREAD

**Issue by nefarius** [nefarius/Nefarius.Drivers.HidHide#8]
Investigate:

```
2023-09-26 12:16:56 [ERR] [HidHide] Failed to self-whitelist for HidHide
System.ArgumentException: The supplied file path doesn't exist (Parameter 'path')
   at Nefarius.Drivers.HidHide.Util.VolumeHelper.PathToDosDevicePath(String path)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Nefarius.Drivers.HidHide.Util.MultiSzHelper.StringArrayToMultiSzPointer(IEnumerable`1 instances, Int32& length)
   at Nefarius.Drivers.HidHide.HidHideControlService.AddApplicationPath(String path)
   at DSX.ViewModels.HidHidePageViewModel..ctor(HidHideControlService hidHideControlService, ILogger logger)
```

**Comment by nefarius** [comment]
Got fixed today.
